from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WELCOME_IMAGE_PATH = PROJECT_ROOT / "assets" / "welcome.png"
MAIN_MENU_IMAGE_PATH = PROJECT_ROOT / "assets" / "main_menu.png"
MY_CONNECTIONS_IMAGE_PATH = PROJECT_ROOT / "assets" / "my_connections.png"
PROFILE_IMAGE_PATH = PROJECT_ROOT / "assets" / "profile.png"
BUY_ACCESS_IMAGE_PATH = PROJECT_ROOT / "assets" / "buy_access.png"
BUY_RUB_TARIFFS_IMAGE_PATH = PROJECT_ROOT / "assets" / "buy_rub_tariffs.png"
BUY_PROMO_IMAGE_PATH = PROJECT_ROOT / "assets" / "buy_promo.png"
BUY_RUB_PAYMENT_IMAGE_PATH = PROJECT_ROOT / "assets" / "buy_rub_payment.png"
SUPPORT_IMAGE_PATH = PROJECT_ROOT / "assets" / "support.png"
WINDOWS_MAC_GUIDE_IMAGE_PATH = PROJECT_ROOT / "assets" / "windows_mac.png"
INSTRUCTIONS_WINDOWS_MAC_IMAGE_PATH = PROJECT_ROOT / "assets" / "instructions_windows_mac.png"
IPHONE_GUIDE_IMAGE_PATH = PROJECT_ROOT / "assets" / "iphone.png"
INSTRUCTIONS_IOS_APPS_IMAGE_PATH = PROJECT_ROOT / "assets" / "instructions_ios_apps.png"
INSTRUCTIONS_IOS_IPHONE_DETAIL_IMAGE_PATH = PROJECT_ROOT / "assets" / "instructions_ios_iphone_detail.png"
ANDROID_TRIAL_GUIDE_IMAGE_PATH = PROJECT_ROOT / "assets" / "android.png"
ANDROID_INSTRUCTIONS_APPS_IMAGE_PATH = PROJECT_ROOT / "assets" / "android_instructions.png"
ANDROID_INSTRUCTIONS_HAPP_IMAGE_PATH = PROJECT_ROOT / "assets" / "instructions_android_happ.png"
ANDROID_INSTRUCTIONS_HIDDIFY_IMAGE_PATH = PROJECT_ROOT / "assets" / "instructions_android_hiddify.png"
ANDROID_INSTRUCTIONS_V2RAYTUN_IMAGE_PATH = PROJECT_ROOT / "assets" / "instructions_android_v2raytun.png"
VPN_TROUBLESHOOT_IMAGE_PATH = PROJECT_ROOT / "assets" / "vpn_troubleshoot.png"
VPN_TROUBLESHOOT_SUCCESS_IMAGE_PATH = PROJECT_ROOT / "assets" / "vpn_troubleshoot_success.png"
INSTRUCTIONS_IMAGE_PATH = PROJECT_ROOT / "assets" / "instructions.png"
